// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Splitly.Api.Database;

#nullable disable

namespace Splitly.Api.Database.Migrations
{
    [DbContext(typeof(SplitlyDbContext))]
    partial class SplitlyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Splitly.Api.Domain.Expense", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("ExpenseGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_group_id");

                    b.Property<Guid>("PaidById")
                        .HasColumnType("uuid")
                        .HasColumnName("paid_by_id");

                    b.Property<DateOnly>("SpentOn")
                        .HasColumnType("date")
                        .HasColumnName("spent_on");

                    b.Property<Guid[]>("SplitAmong")
                        .IsRequired()
                        .HasColumnType("uuid[]")
                        .HasColumnName("split_among");

                    b.HasKey("Id")
                        .HasName("pk_expenses");

                    b.HasIndex("ExpenseGroupId")
                        .HasDatabaseName("ix_expenses_expense_group_id");

                    b.ToTable("expenses", (string)null);
                });

            modelBuilder.Entity("Splitly.Api.Domain.ExpenseGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_expense_groups");

                    b.ToTable("expense_groups", (string)null);
                });

            modelBuilder.Entity("Splitly.Api.Domain.Participant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ExpenseGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("expense_group_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_participants");

                    b.HasIndex("ExpenseGroupId")
                        .HasDatabaseName("ix_participants_expense_group_id");

                    b.ToTable("participants", (string)null);
                });

            modelBuilder.Entity("Splitly.Api.Domain.Expense", b =>
                {
                    b.HasOne("Splitly.Api.Domain.ExpenseGroup", null)
                        .WithMany("Expenses")
                        .HasForeignKey("ExpenseGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_expenses_expense_groups_expense_group_id");
                });

            modelBuilder.Entity("Splitly.Api.Domain.Participant", b =>
                {
                    b.HasOne("Splitly.Api.Domain.ExpenseGroup", null)
                        .WithMany("Participants")
                        .HasForeignKey("ExpenseGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_participants_expense_groups_expense_group_id");
                });

            modelBuilder.Entity("Splitly.Api.Domain.ExpenseGroup", b =>
                {
                    b.Navigation("Expenses");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
